/* definition of the proverb objects Arrays categorized by continent name*/
const asiaArr=[{Proverb: 'Fall seven times, stand up eight.',Source: 'Japanese Proverb'},{Proverb: 'Do good and throw it in the sea.',Source: 'Arab Proverb'},{Proverb: 'Where love reigns, the impossible may be attained.',Source: 'Indian Proverb'},{Proverb: 'It’s better to light a candle than curse the darkness.',Source: 'Chinese Proverb'},{Proverb: 'Measure a thousand times and cut once.',Source: 'Turkish Proverb'},{Proverb: 'In a battle between elephants, the ants get squashed.',Source: 'Thai Proverb'},{Proverb: 'If you take big paces, you leave big spaces.',Source: 'Burmese Proverb'},{Proverb: 'Give a man a fish, and you feed him for a day. Teach a man to fish, and you feed him for a lifetime.',Source: 'Chinese Proverb'},{Proverb: 'What you see in yourself is what you see in the world.',Source: 'Afghan Proverb'},{Proverb: 'Examine what is said, not who speaks.',Source: 'Arab Proverb'},{Proverb: 'Deep doubts, deep wisdom; small doubts, small wisdom.',Source: 'Chinese Proverb'},{Proverb: 'A man does not seek his luck; luck seeks its man.',Source: 'Turkish Proverb'},{Proverb: 'The reputation of a thousand years may be determined by the conduct of one hour.',Source: 'Japanese Proverb'},{Proverb: 'The journey of a thousand miles starts with a single step.',Source: 'Chinese Proverb'},{Proverb: 'A man grows most tired while standing still.',Source: 'Chinese Proverb'},{Proverb: 'When the winds of change blow, some people build walls, and others build windmills.',Source: 'Chinese Proverb'},{Proverb: 'Dig the well before you are thirsty.',Source: 'Chinese Proverb'},{Proverb: 'If your face is ugly, you can’t blame the mirror.',Source: 'Chinese Proverb'},{Proverb: 'Keep your broken arm inside your sleeve.',Source: 'Chinese Proverb'},{Proverb: 'The Fallen blossom doesn’t return to the branch.',Source: 'Japanese Proverb'},{Proverb: 'If you look up, there are no limits.',Source: 'Japanese Proverb'},{Proverb: 'Work the fields on a beautiful day, study on a rainy day.',Source: 'Japanese Proverb'},{Proverb: 'Knowledge without wisdom is a load of books on fools back.',Source: 'Japanese Proverb'},{Proverb: 'If you wish to learn the highest truths, begin with the alphabet.',Source: 'Japanese Proverb'},{Proverb: 'Complaining is the weak man’s weapon.',Source: 'Indian Proverb'},{Proverb: 'Advice sharpens a rusty opinion.',Source: 'Indian Proverb'}];
const africaArr=[{Proverb: 'If you want to go fast, go alone. If you want to go far, go together.',Source: 'African Proverb'},{Proverb: 'A man who uses force is afraid of reasoning.',Source: 'Kenyan Proverb'},{Proverb: 'He who does not travel, does not know the value of men.',Source: 'Moorish Proverb'},{Proverb: 'The most beautiful fig may contain a worm.',Source: 'Zulu Proverb'},{Proverb: 'Evil enters like a needle and spreads like an oak tree.',Source: 'Ethiopian Proverb'},{Proverb: 'It takes a whole village to raise a child.',Source: 'African Proverb'},{Proverb: 'Instruction in youth is like engraving in stone.',Source: 'Moroccan Proverb'},{Proverb: 'A beautiful thing is never perfect.',Source: 'Egyptian Proverb'},{Proverb: 'A fault confessed is half redressed.',Source: 'Zulu Proverb'},{Proverb: 'No man can paddle two canoes at the same time.',Source: 'Bantu Proverb'},{Proverb: 'To get lost is to learn the way',Source: 'African Proverb'},{Proverb: 'Many hands make light work',Source: 'Tanzanian proverb'},{Proverb: 'Wisdom does not come overnight',Source: 'Somali Proverb'},{Proverb: 'The eye never forgets what the heart has seen',Source: 'African Proverb'},{Proverb: 'If you want to go fast, go alone. If you want to go far, go together',Source: 'African Proverb'},{Proverb: 'Where a woman rules, streams run uphill',Source: 'Ethiopian Proverb'},{Proverb: 'Wisdom is like fire. People take it from others',Source: 'Congolese Proverb'},{Proverb: 'Only a wise person can solve a difficult problem —',Source: 'Akan'},{Proverb: 'An army of sheep led by a lion can defeat an army of lions led by a sheep —',Source: 'Ghanaian'},{Proverb: 'A small house will hold a hundred friends — African proverb',Source: 'African Proverb'},{Proverb: 'In the moment of crisis, the wise build bridges and the foolish build dams — Nigerian',Source: 'Nigerian'},{Proverb: 'If you are filled with pride, then you will have no room for wisdom — African proverb',Source: 'African Proverb'},{Proverb: 'A wise person will always find a way — Tanzanian',Source: 'Tanzanian Proverb'},{Proverb: 'Dine with a stranger but save your love for your family — Ethiopian proverb',Source: 'Ethiopian Proverb'}];
const europeArr=[{Proverb: 'Shared joy is a double joy; shared sorrow is half a sorrow.',Source: 'Swedish Proverb'},{Proverb: 'Words should be weighed, not counted.',Source: 'Yiddish Proverb'},{Proverb: 'If you can’t live longer, live deeper.',Source: 'Italian Proverb'},{Proverb: 'Still waters run deep.',Source: 'Latin Proverb'},{Proverb: 'The night rinses what the day has soaped.',Source: 'Swiss Proverb'},{Proverb: 'A spoon does not know the taste of soup, nor a learned fool the taste of wisdom.',Source: 'Welsh Proverb'},{Proverb: 'Change yourself and fortune will change.',Source: 'Portuguese Proverb'},{Proverb: 'In love, there is always one who kisses and one who offers the cheek.',Source: 'French Proverb'},{Proverb: 'Who begins too much accomplishes little.',Source: 'German Proverb'},{Proverb: 'Whoever gossips to you will gossip about you.',Source: 'Spanish Proverb'},{Proverb: 'Beauty lies in the eye of the beholder.',Source: 'English Proverb'},{Proverb: 'Don’t sail out farther than you can row back.',Source: 'Danish Proverb'},{Proverb: 'There is no shame in not knowing; the shame lies in not finding out.',Source: 'Russian Proverb'},{Proverb: 'Age is honorable and youth is noble.',Source: 'Irish Proverb'},{Proverb: 'Before you score, you first must have a goal.',Source: 'Greek Proverb'},{Proverb: 'Good advice is often annoying, bad advice never is.',Source: 'French Proverb'},{Proverb: 'Do not rejoice at my grief, for when mine is old, yours will be new.',Source: 'Spanish Proverb'},{Proverb: 'Two wrongs don’t make a right.',Source: 'English Proverb'},{Proverb: 'A large chair does not make a king.',Source: 'Sudanese Proverb'},{Proverb: 'A teacher is better than two books.',Source: 'German Proverb'},{Proverb: 'Character is always corrupted by prosperity.',Source: 'Icelandic Proverb'},{Proverb: 'To be willing is only half the task.',Source: 'Armenian Proverb'},{Proverb: 'Everyone is kneaded out of the same dough, but not baked in the same oven.',Source: 'Yiddish Proverb'},{Proverb: 'The heart that loves is always young.',Source: 'Greek Proverb'},{Proverb: 'He who always thinks it is too soon is sure to come too late.',Source: 'German Proverb'},{Proverb: 'Speak the truth, but leave immediately after.',Source: 'Slovenian Proverb'}];

/*function that generates a random limit between 0 and the number upperLimit)*/ 
function randomNumberGenerator(upperLimit){
    return (Math.floor(Math.random()*upperLimit));
}

asiaIndex=randomNumberGenerator(asiaArr.length);
africaIndex=randomNumberGenerator(africaArr.length);
europeIndex=randomNumberGenerator(europeArr.length);
asiaProverb=asiaArr[asiaIndex];
africaProverb=africaArr[africaIndex];
europeProverb=europeArr[europeIndex];
console.log(`Proverb from Asia: ${asiaArr[asiaIndex]['Proverb']}
            Proverb from Africa: ${africaArr[africaIndex]['Proverb']}
            Proverb from Europe: ${europeArr[europeIndex]['Proverb']}`);
            